name: Python Application CI

on: [push, pull_request] # Bu workflow ne zaman tetiklensin? (Kod gönderince veya PR açınca)

jobs:
  build:
    runs-on: ubuntu-latest # Hangi işletim sisteminde çalışsın? (Genelde Linux kullanılır)

    steps:
    - uses: actions/checkout@v3 # 1. Kodu GitHub'dan alıp sanal makineye kopyala

    - name: Set up Python 3.10 # 2. Python 3.10 sürümünü kur (GÜNCELLENDİ)
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' # <--- DEĞİŞİKLİK BURADA

    - name: Install dependencies # 3. requirements.txt dosyasındaki bağımlılıkları kur
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8 (Örnek Test Adımı) # 4. Basit bir kod stili/kalite kontrolü yap
      run: |
        pip install flake8
        # Kod stilini kontrol et (Şimdilik hata bulsa bile workflow'u durdurmasın diye || true ekledik)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true