name: Python Application CI
permissions:
  actions: read
  contents: read
  security-events: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 # 1. Kodu al

    - name: Set up Python 3.10 # 2. Python'u kur
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies # 3. Bağımlılıkları kur
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # --- YENİ GÜVENLİK ADIMLARI ---
    - name: Initialize CodeQL # 4. CodeQL'i başlat ve analiz için hazırla
      uses: github/codeql-action/init@v3
      with:
        languages: python # Analiz edilecek dil: Python

    - name: Autobuild # 5. CodeQL'in kodu analiz etmek için build etmesi (Python için basit projelerde otomatik çalışır)
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis # 6. CodeQL analizini gerçekleştir ve sonuçları yükle
      uses: github/codeql-action/analyze@v3
    # --- YENİ GÜVENLİK ADIMLARI BİTTİ ---

    - name: Lint with flake8 (Örnek Test Adımı) # 7. Kod stilini kontrol et
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true