name: Python Application CI

permissions:
  actions: read
  contents: read
  security-events: write

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ] # PR açıldığında, güncellendiğinde, yeniden açıldığında tetikle
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest # Hangi işletim sisteminde çalışsın?

    steps:
    - uses: actions/checkout@v3 # 1. Kodu al

    - name: Set up Python 3.10 # 2. Python 3.10'u kur
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies # 3. Bağımlılıkları kur
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize CodeQL # 4. CodeQL'i başlat
      uses: github/codeql-action/init@v3
      with:
        languages: python

    - name: Autobuild # 5. CodeQL için build et
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis # 6. CodeQL analizini yap
      uses: github/codeql-action/analyze@v3

    - name: Lint with flake8 (Örnek Test Adımı) # 7. Kod stilini kontrol et
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true