name: PR Checks and Main Branch Docker Push

permissions:
  actions: read
  contents: read      # CodeQL ve Docker build için kodu checkout etme izni
  security-events: write # CodeQL ve Trivy SARIF sonuçlarını Güvenlik sekmesine yükleme izni
  packages: write      # GHCR'ye imaj gönderebilmek için GITHUB_TOKEN'a yazma izni

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]
  push:
    branches:
      - main # 'main' branch'i için push olaylarında tetiklenir

jobs:
  analyze_and_scan_pr: # İş adını PR için daha belirgin hale getirdim
    name: CodeQL and Trivy Analysis (Pull Request)
    if: github.event_name == 'pull_request_target' # Bu job sadece pull_request_target olayında çalışsın
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (Pull Request Head)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Autobuild (for CodeQL)
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Build Docker image for PR
        run: |
          IMAGE_TAG="pr-${{ github.event.pull_request.number }}"
          # PR imajına farklı bir isim verelim ki GHCR'deki main imajıyla karışmasın
          docker build -t guvenli-not-defteri-pr:$IMAGE_TAG . 
          echo "IMAGE_NAME_WITH_TAG_PR=guvenli-not-defteri-pr:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Run Trivy vulnerability scanner on PR image
        uses: aquasec/trivy-action@0.24.0 # Belirli bir versiyon kullanmak daha stabildir
        with:
          image-ref: ${{ env.IMAGE_NAME_WITH_TAG_PR }}
          format: 'table'
          exit-code: '0' 
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'
          # output: 'trivy-results.sarif' # SARIF istenirse

      # İsteğe Bağlı Adım: Trivy SARIF sonuçlarını GitHub Güvenlik Sekmesine Yükleme
      # - name: Upload Trivy scan results to GitHub Security tab (PR)
      #   if: success() || failure() # Her durumda çalışsın (eğer SARIF dosyası oluştuysa)
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: 'trivy-results.sarif' # trivy-action'da output olarak trivy-results.sarif belirtilmişse

  build_and_push_to_ghcr:
    name: Build and Push Docker image to GHCR
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Sadece main branch'e push yapıldığında çalışsın
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository (Main Branch)
        uses: actions/checkout@v4
        # main branch'e push yapıldığı için ref belirtmeye gerek yok, varsayılan olarak o branch'i alır.

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/guvenli-not-defteri 
          # ghcr.io/KULLANICI_ADIN/IMAGE_ADIN formatında olmalı
          tags: |
            type=sha,prefix=,suffix=,format=short 
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Check for Dummy API Key
        run: |
          if [ -n "${{ secrets.DUMMY_API_KEY }}" ]; then
            echo "Dummy API Key secret is configured and accessible."
            echo "First 3 chars of API Key: ${{ secrets.DUMMY_API_KEY:0:3 }}***" 
          else
            echo "WARNING: Dummy API Key secret is NOT configured!"
            # exit 1 # Secret yoksa build'i burada durdurmak istersen bu satırı aktif et
          fi

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}